spring.application.name=observability-and-load-testing

# Database - Postgresql
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/api-observability-and-load-testing}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# hibernate-sql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99