spring.application.name=observability-and-load-testing

# Database - Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/api-observability-and-load-testing
spring.datasource.username=username
spring.datasource.password=password

# hibernate-sql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
